### ISSUE TITLE
Think about behavior of inputs in forms

### ISSUE THREAD

**Issue by fabiomontefuscolo** [hoarrd/drunken-parrot-flat-ui#4]
It's hard to navigate in a large form without using the Tab key.I don't know why, but I can't setup tabindex property directly in `<label>`. I setup tabindex in `<span class="icon">` and it worked. To select the radio using spacebar, I had to trigger the click event in label and it also worked.

I think it would be nice if drunken-parrot implements those defaults behaviors in forms, but I don't know how to pull request this. In my app I did this as an workaround:

```javascript
    (function($){
        $(function () {
            $('.form-group .radio .icons,:input:visible').each(function(i) {
                var $this = $(this);
                $this.prop('tabindex', i + 1);
            });
        });

        $(document).on('keydown.radio.data-api', '[data-toggle^=radio], .radio', function (e) {
            if(e.keyCode === 32){
                $(this).trigger('click.radio.data-api');
            }
        });
    })(jQuery);
```

**Comment by hoarrd** [comment]
Thanks @fabiomontefuscolo, we will incorporate your changes into our code.
